package com.padis.business.xzqhwh.qhdmbgqkhztj;

import com.padis.common.xtservice.connection.ConnConfig;

import ctais.services.data.DataWindow;
import ctais.services.or.UserTransaction;
/**
 * <p> 
 * Description: 汇总统计区划变更情况服务类（QhdmbgqkhztjService）的manager,提供QhdmbgqkhztjService底层处理的方法
 * </p> 
 * <p>
 * Copyright: Copyright (c) digitalchina 2007
 * </p>
 * <p>
 * Company: digitalchina
 * </p>
 * 
 * @since 2010-06-11
 * @author lijl
 * @version 1.0
 */

public class QhdmbgqkhztjManager {

	/**
	 * <p>方法名称：</p>
	 * <p>方法描述：</p>
	 * @return 汇总结果
	 * @throws Exception
	 * @author lijl
	 * @since 2010-05-07
	 */
	public void queryHzbByBglx(String hzsjq, String hzsjz, String hzmc) throws Exception {
		StringBuffer sql = new StringBuffer("INSERT INTO XZQH_BGLXHZB(HZMC,XZQH_MC,XZQH_DM,SJ_XZQH_DM,JC_DM,XINZENG,BIANGENG,BINGRU,QIANYI) ")
				.append("SELECT '").append(hzmc).append("',V.XZQH_MC,V.XZQH_DM,V.SJ_XZQH_DM,V.JCDM,NVL(A.XINZENG,0) XINZENG,NVL(A.BIANGENG,0) BIANGENG,NVL(A.BINGRU,0) BINGRU,NVL(A.QIANYI,0) QIANYI FROM ")
				.append("(SELECT SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)||'0000000000000' SJXZQH_DM,")
				.append("SUM(DECODE(M.BGLX_DM,'11',1,0)) XINZENG,SUM(DECODE(M.BGLX_DM,'21',1,0)) BIANGENG,")
				.append("SUM(DECODE(M.BGLX_DM,'31',1,0)) BINGRU,SUM(DECODE(M.BGLX_DM,'41',1,0)) QIANYI")
				.append(" FROM XZQH_BGMXB M WHERE ");
				if(!hzsjq.equals("")){
					sql.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
				}
				if(!hzsjz.equals("")){
					if(!hzsjq.equals("")){
						sql.append(" AND ");
					}
					sql.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
				}
				sql.append(" GROUP BY SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)")
				.append(") A,V_DM_XZQH V")
				.append(" WHERE A.SJXZQH_DM(+) = V.XZQH_DM AND V.JCDM=1")
				.append(" UNION ALL ")
				.append("SELECT '").append(hzmc).append("','全国' XZQH_MC,'999999999999999' XZQH_DM,'000000000000000','0',")
				.append("SUM(DECODE(M.BGLX_DM,'11',1,0)) XINZENG,SUM(DECODE(M.BGLX_DM,'21',1,0)) BIANGENG,")
				.append("SUM(DECODE(M.BGLX_DM,'31',1,0)) BINGRU,SUM(DECODE(M.BGLX_DM,'41',1,0)) QIANYI")
				.append(" FROM XZQH_BGMXB M WHERE ");
				if(!hzsjq.equals("")){
					sql.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
				}
				if(!hzsjz.equals("")){
					if(!hzsjq.equals("")){
						sql.append(" AND ");
					}
					sql.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
				}
		StringBuffer sql1 = new StringBuffer("INSERT INTO XZQH_BGLXHZB(HZMC,XZQH_MC,XZQH_DM,SJ_XZQH_DM,JC_DM,XINZENG,BIANGENG,BINGRU,QIANYI) ")
				.append("SELECT '").append(hzmc).append("',V.XZQH_MC,V.XZQH_DM,V.SJ_XZQH_DM,V.JCDM,NVL(A.XINZENG,0) XINZENG,NVL(A.BIANGENG,0) BIANGENG,NVL(A.BINGRU,0) BINGRU,NVL(A.QIANYI,0) QIANYI FROM ")
				.append("(SELECT SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,4)||'00000000000' SJXZQH_DM,")
				.append("SUM(DECODE(M.BGLX_DM,'11',1,0)) XINZENG,SUM(DECODE(M.BGLX_DM,'21',1,0)) BIANGENG,")
				.append("SUM(DECODE(M.BGLX_DM,'31',1,0)) BINGRU,SUM(DECODE(M.BGLX_DM,'41',1,0)) QIANYI")
				.append(" FROM XZQH_BGMXB M WHERE ");
				if(!hzsjq.equals("")){
					sql1.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
				}
				if(!hzsjz.equals("")){
					if(!hzsjq.equals("")){
						sql1.append(" AND ");
					}
					sql1.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
				}
				sql1.append(" GROUP BY SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,4)")
				.append(") A,V_DM_XZQH V")
				.append(" WHERE A.SJXZQH_DM(+) = V.XZQH_DM AND V.JCDM=2");
				
		StringBuffer sql2 = new StringBuffer("INSERT INTO XZQH_BGLXHZB(HZMC,XZQH_MC,XZQH_DM,SJ_XZQH_DM,JC_DM,XINZENG,BIANGENG,BINGRU,QIANYI) ")
				.append("SELECT '").append(hzmc).append("',V.XZQH_MC,V.XZQH_DM,V.SJ_XZQH_DM,V.JCDM,NVL(A.XINZENG,0) XINZENG,NVL(A.BIANGENG,0) BIANGENG,NVL(A.BINGRU,0) BINGRU,NVL(A.QIANYI,0) QIANYI FROM ")
				.append("(SELECT SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,6)||'000000000' SJXZQH_DM,")
				.append("SUM(DECODE(M.BGLX_DM,'11',1,0)) XINZENG,SUM(DECODE(M.BGLX_DM,'21',1,0)) BIANGENG,")
				.append("SUM(DECODE(M.BGLX_DM,'31',1,0)) BINGRU,SUM(DECODE(M.BGLX_DM,'41',1,0)) QIANYI")
				.append(" FROM XZQH_BGMXB M WHERE ");
				if(!hzsjq.equals("")){
					sql2.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
				}
				if(!hzsjz.equals("")){
					if(!hzsjq.equals("")){
						sql2.append(" AND ");
					}
					sql2.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
				}
				sql2.append(" GROUP BY SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,6)")
				.append(") A,V_DM_XZQH V")
				.append(" WHERE A.SJXZQH_DM(+) = V.XZQH_DM AND V.JCDM=3");
			
		UserTransaction ut = new UserTransaction();
		try{
			ut.begin();
			//this.deleteHzb("XZQH_BGLXHZB", ut);
			DataWindow dw = DataWindow.dynamicCreate(sql.toString());
			dw.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw.setTransObject(ut);
			dw.update(false);
			DataWindow dw1 = DataWindow.dynamicCreate(sql1.toString());
			dw1.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw1.setTransObject(ut);
			dw1.update(false);
			DataWindow dw2 = DataWindow.dynamicCreate(sql2.toString());
			dw2.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw2.setTransObject(ut);
			dw2.update(false);
			ut.commit();
		}catch(Exception e){
			ut.rollback();
			throw e;
		}
	}
	
	/**
	 * <p>方法名称：queryHzbByJbLx</p>
	 * <p>方法描述：汇总全国区划变更情况</p>
	 * @return 汇总结果
	 * @throws Exception
	 * @author lijl
	 * @since 2010-05-07
	 */
	public void queryHzbByJbLx(String hzsjq, String hzsjz, String hzmc) throws Exception {
		
		StringBuffer sql = new StringBuffer("INSERT INTO XZQH_QHJBHBGLXHZB(HZMC,BGLX_MC,BGLX_DM,BGS_SHENG,BGS_SHI,BGS_XIAN,BGS_XIANG,BGS_CUN,BGS_XIAOJI) ")
		.append("SELECT '").append(hzmc).append("',B.BGLX_MC,B.BGLX_DM,NVL(A.SHENGJI,0) SHENGJI,NVL(A.SHIJI,0) SHIJI,NVL(A.XIANJI,0) XIANJI,NVL(A.XIANGJI,0) XIANGJI,NVL(A.CUNJI,0) CUNJI,NVL(A.XIAOJI,0) XIAOJI FROM (SELECT M.BGLX_DM,")
		.append("           SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'1',1,0)) SHENGJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'2',1,0)) SHIJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'3',1,0)) XIANJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'4',1,0)) XIANGJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'5',1,'6',1,0)) CUNJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,null,0,1)) XIAOJI")
		.append("  FROM XZQH_BGMXB M WHERE ");
		if(!hzsjq.equals("")){
			sql.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
		}
		if(!hzsjz.equals("")){
			if(!hzsjq.equals("")){
				sql.append(" AND ");
			}
			sql.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
		}
		sql.append("  GROUP BY M.BGLX_DM) A,V_DM_XZQH_BGLX B")
		.append("  WHERE A.BGLX_DM = B.BGLX_DM")	
		.append("  ")
		.append("  UNION ALL ")
		.append("  ")
		.append("  SELECT '").append(hzmc).append("','合计' BGLX_MC,'99' BGLX_DM,")
		.append("           SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'1',1,0)) SHENGJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'2',1,0)) SHIJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'3',1,0)) XIANJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'4',1,0)) XIANGJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,'5',1,'6',1,0)) CUNJI,")
		.append("      SUM(DECODE(CASE ")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		.append("          WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		.append("          ELSE '6'")
		.append("      END,null,0,1)) XIAOJI")
		.append("  FROM XZQH_BGMXB M WHERE ");
		if(!hzsjq.equals("")){
			sql.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
		}
		if(!hzsjz.equals("")){
			if(!hzsjq.equals("")){
				sql.append(" AND ");
			}
			sql.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
		}
	
		UserTransaction ut = new UserTransaction();
		try{
			ut.begin();
			//this.deleteHzb("XZQH_QHJBHBGLXHZB", ut);
			DataWindow dw = DataWindow.dynamicCreate(sql.toString());
			dw.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw.setTransObject(ut);
			dw.update(false);
			ut.commit();
		}catch(Exception e){
			ut.rollback();
			throw e;
		}
	}
	
	/**
	 * <p>方法名称：queryHzbByQhjb</p>
	 * <p>方法描述：按区划级别汇总区划变更情况</p>
	 * @return 汇总结果
	 * @throws Exception
	 * @author lijl
	 * @since 2010-05-07
	 */
	public void queryHzbByQhjb(String hzsjq, String hzsjz, String hzmc) throws Exception {
		
		StringBuffer sql = new StringBuffer("INSERT INTO XZQH_JBHZB(HZMC,XZQH_MC,XZQH_DM,SJ_XZQH_DM,JC_DM,BGS_SHENG,BGS_SHI,BGS_XIAN,BGS_XIANG,BGS_CUN)")
			.append(" SELECT '").append(hzmc).append("',V.XZQH_MC,V.XZQH_DM,V.SJ_XZQH_DM,V.JCDM,NVL(A.SHENGJI,0) SHENGJI,NVL(A.SHIJI,0) SHIJI,NVL(A.XIANJI,0) XIANJI,NVL(A.XIANGJI,0) XIANGJI,NVL(A.CUNJI,0) CUNJI FROM ")
            .append("(SELECT SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)||'0000000000000' SJXZQH_DM,")
            .append(" SUM(DECODE(CASE") 
            .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
            .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
            .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
        	.append(" ELSE '6'")
        	.append(" END,'1',1,0)) SHENGJI,")
        	.append(" SUM(DECODE(CASE ")
            .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
            .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
        	.append(" ELSE '6'")
        	.append("  END,'2',1,0)) SHIJI,")
        	.append("  SUM(DECODE(CASE ")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
        	.append("      ELSE '6'")
        	.append(" END,'3',1,0)) XIANJI,")
        	.append(" SUM(DECODE(CASE ")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
        	.append("  ELSE '6'")
        	.append("  END,'4',1,0)) XIANGJI,")
        	.append(" SUM(DECODE(CASE ")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
        	.append("      ELSE '6'")
        	.append(" END,'5',1,'6',1,0)) CUNJI")
        	.append(" FROM XZQH_BGMXB M WHERE ");
			if(!hzsjq.equals("")){
				sql.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
			}
			if(!hzsjz.equals("")){
				if(!hzsjq.equals("")){
					sql.append(" AND ");
				}
				sql.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
			}
        	sql.append(" GROUP BY SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)) A,V_DM_XZQH V")
        	.append(" WHERE A.SJXZQH_DM(+) = V.XZQH_DM AND V.JCDM=1")
        	.append(" UNION ALL ")
  
        	.append(" SELECT '").append(hzmc).append("','全国' XZQH_MC,'999999999999999' XZQH_DM,'000000000000000','0',")
        	.append(" SUM(DECODE(CASE ")
        	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
			.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		    .append("      ELSE '6'")
		    .append("  END,'1',1,0)) SHENGJI,")
		    .append("  SUM(DECODE(CASE ")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		    .append("      ELSE '6'")
		    .append("  END,'2',1,0)) SHIJI,")
		    .append("  SUM(DECODE(CASE ")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		    .append("      ELSE '6'")
		    .append("  END,'3',1,0)) XIANJI,")
		    .append("  SUM(DECODE(CASE ")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		    .append("      ELSE '6'")
		    .append("  END,'4',1,0)) XIANGJI,")
		    .append("  SUM(DECODE(CASE ")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
		    .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
		    .append("      ELSE '6'")
		    .append("  END,'5',1,'6',1,0)) CUNJI")
		    .append(" FROM XZQH_BGMXB M WHERE ");
		if(!hzsjq.equals("")){
			sql.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
		}
		if(!hzsjz.equals("")){
			if(!hzsjq.equals("")){
				sql.append(" AND ");
			}
			sql.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
		}

		StringBuffer sql1 = new StringBuffer("INSERT INTO XZQH_JBHZB(HZMC,XZQH_MC,XZQH_DM,SJ_XZQH_DM,JC_DM,BGS_SHENG,BGS_SHI,BGS_XIAN,BGS_XIANG,BGS_CUN)")
		.append(" SELECT '").append(hzmc).append("',V.XZQH_MC,V.XZQH_DM,V.SJ_XZQH_DM,V.JCDM,NVL(A.SHENGJI,0) SHENGJI,NVL(A.SHIJI,0) SHIJI,NVL(A.XIANJI,0) XIANJI,NVL(A.XIANGJI,0) XIANGJI,NVL(A.CUNJI,0) CUNJI FROM ")
        .append("(SELECT SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,4)||'00000000000' SJXZQH_DM,")
        .append(" SUM(DECODE(CASE") 
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append(" ELSE '6'")
    	.append(" END,'1',1,0)) SHENGJI,")
    	.append(" SUM(DECODE(CASE ")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append(" ELSE '6'")
    	.append("  END,'2',1,0)) SHIJI,")
    	.append("  SUM(DECODE(CASE ")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append("      ELSE '6'")
    	.append(" END,'3',1,0)) XIANJI,")
    	.append(" SUM(DECODE(CASE ")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append("  ELSE '6'")
    	.append("  END,'4',1,0)) XIANGJI,")
    	.append(" SUM(DECODE(CASE ")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append("      ELSE '6'")
    	.append(" END,'5',1,'6',1,0)) CUNJI")
    	.append(" FROM XZQH_BGMXB M WHERE ");
		if(!hzsjq.equals("")){
			sql1.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
		}
		if(!hzsjz.equals("")){
			if(!hzsjq.equals("")){
				sql1.append(" AND ");
			}
			sql1.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
		}
    	sql1.append(" GROUP BY SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,4)) A,V_DM_XZQH V")
    	.append(" WHERE A.SJXZQH_DM(+) = V.XZQH_DM AND V.JCDM=2");
    	
		StringBuffer sql2 = new StringBuffer("INSERT INTO XZQH_JBHZB(HZMC,XZQH_MC,XZQH_DM,SJ_XZQH_DM,JC_DM,BGS_SHENG,BGS_SHI,BGS_XIAN,BGS_XIANG,BGS_CUN)")
		.append(" SELECT '").append(hzmc).append("',V.XZQH_MC,V.XZQH_DM,V.SJ_XZQH_DM,V.JCDM,NVL(A.SHENGJI,0) SHENGJI,NVL(A.SHIJI,0) SHIJI,NVL(A.XIANJI,0) XIANJI,NVL(A.XIANGJI,0) XIANGJI,NVL(A.CUNJI,0) CUNJI FROM ")
        .append("(SELECT SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,6)||'000000000' SJXZQH_DM,")
        .append(" SUM(DECODE(CASE") 
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append(" ELSE '6'")
    	.append(" END,'1',1,0)) SHENGJI,")
    	.append(" SUM(DECODE(CASE ")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
        .append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append(" ELSE '6'")
    	.append("  END,'2',1,0)) SHIJI,")
    	.append("  SUM(DECODE(CASE ")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append("      ELSE '6'")
    	.append(" END,'3',1,0)) XIANJI,")
    	.append(" SUM(DECODE(CASE ")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append("  ELSE '6'")
    	.append("  END,'4',1,0)) XIANGJI,")
    	.append(" SUM(DECODE(CASE ")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 3, 13)='0000000000000' THEN '1'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),3,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 5, 11)='00000000000' THEN '2'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),5,2)<>'00' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 7, 9)='000000000' THEN '3'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),7,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 10, 6)='000000' THEN '4'")
    	.append("      WHEN SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),10,3)<>'000' AND SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM), 13, 3)='000'  THEN '5'")
    	.append("      ELSE '6'")
    	.append(" END,'5',1,'6',1,0)) CUNJI")
    	.append(" FROM XZQH_BGMXB M WHERE ");
		if(!hzsjq.equals("")){
			sql2.append(" M.LRSJ>=TO_DATE('").append(hzsjq).append("','YYYY-MM-DD')");
		}
		if(!hzsjz.equals("")){
			if(!hzsjq.equals("")){
				sql2.append(" AND ");
			}
			sql2.append(" M.LRSJ<=TO_DATE('").append(hzsjz).append("','YYYY-MM-DD')");
		}
    	sql2.append(" GROUP BY SUBSTR(DECODE(M.YSXZQH_DM, NULL, M.MBXZQH_DM, M.YSXZQH_DM),1,6)) A,V_DM_XZQH V")
    	.append(" WHERE A.SJXZQH_DM(+) = V.XZQH_DM AND V.JCDM=3");

		UserTransaction ut = new UserTransaction();
		try{
			ut.begin();
			//this.deleteHzb("XZQH_JBHZB", ut);
			DataWindow dw = DataWindow.dynamicCreate(sql.toString());
			dw.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw.setTransObject(new UserTransaction());
			dw.update(false);
			DataWindow dw1 = DataWindow.dynamicCreate(sql1.toString());
			dw1.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw1.setTransObject(new UserTransaction());
			dw1.update(false);
			DataWindow dw2 = DataWindow.dynamicCreate(sql2.toString());
			dw2.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw2.setTransObject(new UserTransaction());
			dw2.update(false);
			ut.commit();
		}catch(Exception e){
			ut.rollback();
			throw e;
		}
	}
	
	/**
	 * <p>方法名称：deleteHzb</p>
	 * <p>方法描述：删除表数据</p>
	 * @param tableName 表名
	 * @return 无
	 * @throws Exception
	 * @author lijl
	 * @since 2010-06-11
	 */
	private void deleteHzb(String tableName, UserTransaction ut) throws Exception {	
		StringBuffer sql = new StringBuffer("DELETE FROM ").append(tableName).append(" WHERE 1=1");
		DataWindow dw = DataWindow.dynamicCreate(sql.toString());
		dw.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
		dw.setTransObject(ut);
		dw.update(false);
	}
	
	/**
	 * <p>方法名称：deleteHzb</p>
	 * <p>方法描述：删除表数据</p>
	 * @param tableName 表名
	 * @return 无
	 * @throws Exception
	 * @author lijl
	 * @since 2010-06-11
	 */
	public void deleteHzbByHzmc(String hzmc) throws Exception {
		UserTransaction ut = new UserTransaction();
		try{
			ut.begin();
			//删除按变更类型汇总的表数据
			StringBuffer sql = new StringBuffer("DELETE FROM XZQH_BGLXHZB WHERE HZMC='").append(hzmc).append("'");
			DataWindow dw = DataWindow.dynamicCreate(sql.toString());
			dw.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw.setTransObject(ut);
			dw.update(false);
			//删除按区划级别汇总的表数据
			StringBuffer sql1 = new StringBuffer("DELETE FROM XZQH_JBHZB WHERE HZMC='").append(hzmc).append("'");
			DataWindow dw1 = DataWindow.dynamicCreate(sql1.toString());
			dw1.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw1.setTransObject(ut);
			dw1.update(false);
			//删除按变更类型和区划级别汇总的表数据
			StringBuffer sql2 = new StringBuffer("DELETE FROM XZQH_QHJBHBGLXHZB WHERE HZMC='").append(hzmc).append("'");
			DataWindow dw2 = DataWindow.dynamicCreate(sql2.toString());
			dw2.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
			dw2.setTransObject(ut);
			dw2.update(false);
			ut.commit();
		}catch(Exception e){
			ut.rollback();
			throw e;
		}
	}
	
	
	/**
	 * <p>方法名称：groupByHzmc</p>
	 * <p>方法描述：</p>
	 * @return 汇总结果
	 * @throws Exception
	 * @author lijl
	 * @since 2010-05-07
	 */
	public String groupByHzmc() throws Exception {	

		DataWindow dw = DataWindow.dynamicCreate("SELECT B.HZMC FROM XZQH_BGLXHZB B GROUP BY B.HZMC ORDER BY B.HZMC");
		dw.setConnectionName(ConnConfig.getConnectionName(this.getClass()));
		long count = dw.retrieve(); 
		String resultXml = "";
		if (count > 0){
			resultXml = dw.toXML().toString();
		}
		return resultXml;
	}
}
