server:
  port: 7113
  
spring:
  #profiles: peer
  application:
    name: rktcyy-zczx-eurake
    
#Eureka 的服务认证 
security:
  basic:
    enabled: true
  user:
    name: BAPFOPM
    password: 201827
  
eureka:
  instance:
    hostname: eureka-slave2   #代表本地 别名   
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
#默认90s 
    lease-expiration-duration-in-seconds: 15
#服务刷新时间配置，每隔这个时间会主动心跳一次
#默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://BAPFOPM:201827@eureka-master:7111/eureka/,http://BAPFOPM:201827@eureka-slave1:7112/eureka/
      
#eureka server刷新readCacheMap的时间，
#注意，client读取的是readCacheMap，
#这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
#默认30s
  server:
    responseCacheUpdateInvervalMs: 3000
#eureka server缓存readWriteCacheMap失效时间，
#这个只有在这个时间过去后缓存才会失效，失效前不会更新，
#过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
#由于启用了evict其实就用不太上改这个配置了
#默认180s
    responseCacheAutoExpirationInSeconds: 180
#启用主动失效，并且每次主动失效检测间隔为5s
#服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    evictionIntervalTimerInMs: 5000

    
      
      