#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7111/eureka/

#feign
feign:
  hystrix:
    enabled: true
    config:
      stream:
        maxConcurrentConnections: 50
    command:
    default:
      execution:
        timeout:
          enabled: true2
        isolation:
          thread:
            timeoutInMilliseconds: 60000


#server
server:
  port: 8251

#spring
spring:
  application:
    name: bapfopm-pfpsmas-zcms-service
  session:
    store-type: redis
  #datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    ##url: jdbc:mysql://10.1.2.42:3306/xzqh?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/xzqh?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  #redis节点配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0

  http:
    multipart:

      file-size-threshold: 0
      max-file-size: 1MB
      location: E:/YLQHworkspace/upload/temp/
      max-request-size: 10MB

# thymeleaf start
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    suffix: .html
    prefix: classpath:/templates/

#redis集群配置
#redis:
#  cache:
#    clusterNodes:
#    commandTime:
#    expireSeconds:



#PageHelper 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#logging 日志文件存放位置
logging:
  file: E:\YLQHworkspace\rktcyy\${spring.application.name}-${server.port}.log

#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.digital.entity